apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce  
  hostPath:
    path: "/run/desktop/mnt/c/Users/dickison.12/.config/dicki-pv"
    type: DirectoryOrCreate
