apiVersion: v1
kind: Service
metadata:
  name: podinfo-production
spec:
  type: ClusterIP
  selector:
    app: podinfo-production
  ports:
    - name: http
      port: 9898
      protocol: TCP
      targetPort: http
    - port: 9999
      targetPort: grpc
      protocol: TCP
      name: grpc