apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-testing
spec:
  minReadySeconds: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: podinfo-testing
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8686"
      labels:
        app: podinfo-testing
    spec:
      containers:
      - name: podinfo-testing
        image: ghcr.io/stefanprodan/podinfo:6.7.1
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8787
          protocol: TCP
        - name: http-metrics
          containerPort: 8686
          protocol: TCP
        - name: grpc
          containerPort: 8888
          protocol: TCP
        command:
        - ./podinfo
        - --port=8787
        - --port-metrics=8686
        - --grpc-port=8888
        - --grpc-service-name=podinfo-testing
        - --level=info
        - --random-delay=false
        - --random-error=false
        env:
        - name: PODINFO_UI_COLOR
          value: "#34577c"
        livenessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:8787/healthz
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:8787/readyz
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
          - name: data
            mountPath: /data
      volumes:
        - name: data
          emptyDir: {}