apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dicki-deploy-kustomization
resources:
  - podinfo/production/kustomization.yaml
  - podinfo/testing/kustomization.yaml  
  - podinfo/development/kustomization.yaml
  
