apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - podinfo/production/deployment.yaml
  - podinfo/production/hpa.yaml
  - podinfo/production/service.yaml
  - podinfo/development/deployment.yaml
  - podinfo/development/hpa.yaml
  - podinfo/development/service.yaml    
  - podinfo/testing
  
