apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-statefulset
  namespace: dicki-deployments
spec:
  replicas: 2  # Or more, as needed
  serviceName: my-service  # Optional, for DNS
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: busybox:latest  # Replace with your container image
          command: ["sh", "-c", "while true; do echo `date` >> /data/log.txt; sleep 10; done"]
          volumeMounts:
            - name: my-volume
              mountPath: /data
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: my-pvc # This PVC will be created by the StatefulSet
  volumeClaimTemplates:
    - metadata:
        name: my-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "local-storage"
        resources:
          requests:
            storage: 1Gi