apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 1Gi
  storageClassName: "local-storage"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/hostPath"  # Replace with your host directory
    type: DirectoryOrCreate