apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: dicki-deployments
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
  volumeName: my-pv