apiVersion: v1
kind: Service
metadata:
  name: supportstats
  namespace:  dicki-deployments
spec:
  selector:
    app.kubernetes.io/name: supportstats
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: http