apiVersion: apps/v1
kind: Deployment
metadata:
  name: umbracodocker-dev
  namespace:  dicki-deployments
  labels:
    app.kubernetes.io/name: umbracodocker-dev
    middleware.ocio.osu.edu/billing:  dicki-deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: umbracodocker-dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: umbracodocker-dev
      annotations:
        app.kubernetes.io/buildtime: osu-0000000005
    spec:
      restartPolicy: Always
#      imagePullSecrets:
#        - name:  dicki-deployments-registry-pull
      containers:
        - name: umbracodocker-dev
          image: erlenmeyer316/umbraco-v13:v05
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
          ports:
            - name: http-alt
              containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:80"
            - name: ENABLEDEBUGGING
              value: "true"
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          volumeMounts:
            - name: umbracodocker-dev-logs
              mountPath: /app/umbraco/Logs
            - name: umbracodocker-dev-data              
              mountPath: /app/umbraco/Data
            - name: umbracodocker-dev-media
              mountPath: /app/wwwroot/media
            - name: umbracodocker-dev-usync              
              mountPath: /app/uSync
      volumes:
        - name: umbracodocker-dev-logs
          hostPath:
            path: /hostPath/umbraco/Logs
        - name: umbracodocker-dev-data
          hostPath:
            path: /hostPath/umbraco/Data
        - name: umbracodocker-dev-media
          hostPath:
            path: /hostPath/wwwroot/media
        - name: umbracodocker-dev-usync
          hostPath:
            path: /hostPath/umbraco/uSync