apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce  
  hostPath:
    path: /run/desktop/mnt/host/c/Users/dickison.12/.config/dicki-pv/Data
  persistentVolumeReclaimPolicy: Retain      


