apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-media
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /hostPath/umbraco/wwwroot
    type: DirectoryOrCreate     