apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: umbracodocker-dev-media
  namespace:  dicki-deployments
spec:
  spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-media