apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wwwroot
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard    
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/hostPath/wwwroot"
    type: DirectoryOrCreate