apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: umbracodocker-dev-wwwroot
  namespace: dicki-deployments
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi 