apiVersion: v1
kind: Service
metadata:
  name: podinfo-development
spec:
  type: ClusterIP
  selector:
    app: podinfo-development
  ports:
    - name: http
      port: 7676
      protocol: TCP
      targetPort: http
    - port: 7777
      targetPort: grpc
      protocol: TCP
      name: grpc