apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
  labels:
    type: local
    app: umbracodocker-dev
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/c/Users/dickison.12/.kind/persistentVolumes/pv-data"