apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-logs
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/hostPath/umbraco/Logs"
