apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-logs
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/c/Users/dickison.12/.kind/persistentVolumes/pv-logs"
