apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wwwroot
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/wsl/wwwroot/media"
    type: DirectoryOrCreate