apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wwwroot
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/c/Users/dickison.12/.kind/persistentVolumes/pv-wwwroot"