apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wwwroot
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/hostPath/wwwroot/media"