apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: umbracodocker-dev-usync
  namespace:  dicki-deployments
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-data      