apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: umbracodocker-dev-usync
  namespace:  dicki-deployments
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-usync