apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: umbracodocker-dev-usync
  namespace:  dicki-deployments
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  hostPath:
    path: "/mnt/c/Users/dickison.12/.kind/persistentVolumes/pv-usync"