apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: umbracodocker-dev-wwwroot
  namespace:  dicki-deployments
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-wwwroot