apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
spec:
  capacity:
    storage: 1Gi
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce  
  hostPath:
    path: "/run/desktop/mnt/c/Users/dickison.12/.config/dicki-pv/data"
    type: DirectoryOrCreate
