apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce  
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain      

