apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: umbracodocker-dev-logs
  namespace:  dicki-deployments
spec:
  spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeMode: Filesystem