apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: umbracodocker-dev-logs
  namespace:  dicki-deployments
spec:
  spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
  storageClassName: local-storage
  volumeName: pv-logs