apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: umbracodocker-dev-media
  namespace: sem
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: dicki-pv
