apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: umbracodocker-dev-media
  namespace: sem
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem
  volumeName: pvc-28411b09-9243-42e3-b93e-633fc85b4c3d