apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: umbracodocker-dev-data
  namespace: sem
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: managed-nfs-storage 
  volumeMode: Filesystem
  volumeName: pvc-2e2ce12e-1fb5-4ade-a83b-97ee4523ba9e