apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: umbracodocker-dev-media
  namespace:  dicki-deployments
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem
