apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: umbracodocker-dev-logs
  namespace:  dicki-deployments
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: dicki-pv
