apiVersion: v1
kind: Service
metadata:
  name: umbracodocker-dev
  namespace: sem
  labels:
    middleware.ocio.osu.edu/billing: sem
spec:
  selector:
    app.kubernetes.io/name: umbracodocker-dev
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http