apiVersion: v1
kind: Service
metadata:
  name: gitlab-cicd-main
  namespace: sem
  labels:
    middleware.ocio.osu.edu/billing: sem
spec:
  selector:
    app.kubernetes.io/name: gitlab-cicd-main
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http